$(eval $(call addlib,appblockiotest))

# Direct block I/O test (no VFS)
APPBLOCKIOTEST_SRCS-y += $(APPBLOCKIOTEST_BASE)/src/main.c
APPBLOCKIOTEST_SRCS-y += $(APPBLOCKIOTEST_BASE)/src/direct_blk.c

APPBLOCKIOTEST_CINCLUDES-y += -I$(APPBLOCKIOTEST_BASE)/src
